
#*################################################################
#*                                                               #
#*   .::: .:::. :::::. .:::.    ::: :::::.  ::::.  ::.  ::       #
#*  `::. :::.. ::  :: :::..    ::  ::  ::   ::    `::.::         #
#*   ..:: :: :: ::..:: :: ::    ::  :::::.   ::     .:::.        #
#*    ::: :: :: :::::' `:::'    ::  ::  ::  ::::   ::'  ::       #
#*                                                               #
#*                    <<CLOUDY ADVENTURE>>                       #
#*                          v1.2.0                               #
#*             All Images are generated By Gemini 3.5            #
#*   All codes are written by human, it's not a generated game   #
#*                       Author : Rix                            #
#*                                                               #
#*################################################################

import pygame
import os
import datetime
from Platform import *
from Player import *
from Pickups import *
from Settings import *

#* 遊戲模組初始化
pygame.init()
pygame.mixer.init()
clock = pygame.time.Clock()
screen = pygame.display.set_mode((WIDTH,HEIGHT))
pygame.display.set_caption("Platformer Game v1.2.0")

#* 遊玩資料初始化
play_time_per_tick = 0
play_time_s = 0
play_time = str(datetime.timedelta(seconds=play_time_s))
score = 0
data = {"highest_score": 0,
       "total_play_time": play_time,
       "death_count": 0}

running = True
current_platform_speed = PLATFORM_Y_SPEED
platform_change_up = 0
game_state = "START_MENU"

#* 引入字體
font_type = "font/pixel_upgrade.ttf"
def draw_text(surface, text, size, x, y, color, align="center"):
    font = pygame.font.Font(font_type, size)
    text_surface = font.render(text, True, color)
    text_rect = text_surface.get_rect()
    # pygame.draw.rect(text_surface, ORANGE, (0,0,text_rect.width, text_rect.height), 2)
    if align == "left":
        text_rect.left = x
    else:
        text_rect.centerx = x
    text_rect.top = y
    surface.blit(text_surface, text_rect)

#* 引入圖片檔
start_bg = pygame.image.load(os.path.join("img", "start_bg.png")).convert_alpha()

platform1_img = pygame.image.load(os.path.join("img", "platform1.png")).convert_alpha()
platform2_img = pygame.image.load(os.path.join("img", "platform2.png")).convert_alpha()
platform3_img = pygame.image.load(os.path.join("img", "platform3.png")).convert_alpha()

platform_list = [platform1_img, platform2_img, platform3_img]

front_player = pygame.image.load(os.path.join("img", "front_player.png")).convert_alpha()
jump_player = pygame.image.load(os.path.join("img", "jump_player.png")).convert_alpha()
walk_player = pygame.image.load(os.path.join("img", "walk_player.png")).convert_alpha()
background = pygame.image.load(os.path.join("img", "background.png")).convert_alpha()

feather = pygame.image.load(os.path.join("img", "feather.png")).convert_alpha()
jump = pygame.image.load(os.path.join("img", "jump.png")).convert_alpha()
speed = pygame.image.load(os.path.join("img", "speed.png")).convert_alpha()

pickup_list = [speed, jump, feather]

#* 引入音檔
background_music = pygame.mixer.Sound(os.path.join("sound", "background_music.mp3"))
pop_sound = pygame.mixer.Sound(os.path.join("sound", "pop.mp3"))
jump_sound = pygame.mixer.Sound(os.path.join("sound", "jumping.mp3"))

#* 建立群組
players = pygame.sprite.Group()
pickups = pygame.sprite.Group()
platforms = pygame.sprite.Group()
all_sprites = pygame.sprite.Group()

#* 建立玩家、一個平台、把三個群組加入all_sprite
player1 = Player(front_player, walk_player, jump_player, pop_sound, jump_sound)
players.add(player1)

platform1 = Platform(current_platform_speed, platform_list)
platforms.add(platform1)

all_sprites.add(platforms, pickups, players)

#* 生成platforms，當最高平台下降至180到240之間之隨機高度時，生成一個Platform，並隨機生成道具(10%)
def manage_platforms():
    
    highest_platform = min(p.rect.top for p in platforms)
    randomGap = random.randint(140,180)
    
    if highest_platform > randomGap:
        p = Platform(current_platform_speed, platform_list)
        platforms.add(p)
        all_sprites.add(p)
        
        #* 隨機生成道具(由Settings.PICKUPS_SPAWN_RATE決定%)
        r = random.randint(1, PICKUPS_SPAWN_RATE)
        if r == 1:
            manage_pickups(p)

#* 生成道具函式，當平台生成時，道具也有生成(%)，則記錄該平台x、top座標，並配合當前平台速度賦予道具
def manage_pickups(p):
    pickup = Pickups(p, pickup_list)
    pickups.add(pickup)
    all_sprites.add(pickup)
    


background_music.set_volume(background_music.get_volume()/3)
background_music.play(loops=-1)

while running:
    clock.tick(FPS)
    
    #* 取得輸入
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False 
        if event.type == pygame.KEYDOWN:
            if game_state == "START_MENU" and event.key == pygame.K_SPACE:
                game_state = "PLAYING"

    #* 根據狀態進行邏輯更新與畫面渲染
    if game_state == "START_MENU":
        screen.blit(pygame.transform.scale(start_bg, (WIDTH, HEIGHT)), (0, 0))
        draw_text(screen, "最高分數 : " + str(data["highest_score"]), 22, 20, 10, MENU_DATA_COLOR, align="left")
        draw_text(screen, "死亡次數 : " + str(data["death_count"]), 22, 20, 180, MENU_DATA_COLOR, align="left")
        draw_text(screen, "遊戲時間 : " + str(data["total_play_time"]), 22, 20, 40, MENU_DATA_COLOR, align="left")
    
    else:
        #* 邏輯更新
        if not players:
            #* 更新data
            data["death_count"] += 1
            if score > data["highest_score"]:
                data["highest_score"] = score
            data["total_play_time"] = str(datetime.timedelta(seconds=play_time_s))
            
            #* 清除四個群組
            all_sprites.empty()
            platforms.empty()
            players.empty()
            pickups.empty()
            
            #* 初始化設定
            isfirst = True
            Platform.isFirst = True
            platform_change_up = 0
            current_platform_speed = PLATFORM_Y_SPEED
            game_state = "START_MENU"
            score = 0
            
            #* 重新建立
            player1 = Player(front_player, walk_player, jump_player, pop_sound, jump_sound)
            players.add(player1)
            platform1 = Platform(PLATFORM_Y_SPEED, platform_list)
            platforms.add(platform1)
            all_sprites.add(platforms, pickups, players)
            
            #* 生成Platform後，將isFirst關閉
            isfirst = False
        
        score+=1
        platform_change_up+=1
        play_time_per_tick+=1
        
        if play_time_per_tick >= 60:
            play_time_per_tick = 0
            play_time_s += 1
            play_time = str(datetime.timedelta(seconds=play_time_s))
        
        if platform_change_up >= PLATFORM_RATIO_CHANGE_SPAN*60:
            current_platform_speed += current_platform_speed*PLATFORM_Y_SPEED_RATIO
            for p in platforms:
                p.velocity[1] = current_platform_speed 
            platform_change_up = 0
        
        player1.update(platforms, pickups)
        manage_platforms()    
        platforms.update()
        pickups.update()
        
        #* 畫面渲染
        screen.blit(pygame.transform.scale(background, (WIDTH, HEIGHT)), (0,0)) 
        all_sprites.draw(screen)
        draw_text(screen, str(score), 22, WIDTH/2, 10, WHITE)
        draw_text(screen, play_time, 22, WIDTH-60, HEIGHT-50, WHITE)
    
    #* 畫面更新    
    pygame.display.update()

pygame.quit()