
#*################################################################
#*                                                               #
#*   .::: .:::. :::::. .:::.    ::: :::::.  ::::.  ::.  ::       #
#*  `::. :::.. ::  :: :::..    ::  ::  ::   ::    `::.::         #
#*   ..:: :: :: ::..:: :: ::    ::  :::::.   ::     .:::.        #
#*    ::: :: :: :::::' `:::'    ::  ::  ::  ::::   ::'  ::       #
#*                                                               #
#*                    <<CLOUDY ADVENTURE>>                       #
#*                          v1.2.0                               #
#*             All Images are generated By Gemini 3.5            #
#*   All codes are written by human, it's not a generated game   #
#*                       Author : Rix                            #
#*                                                               #
#*################################################################

import pygame
import random
from Settings import *
from Platform import *

class Pickups(pygame.sprite.Sprite):

    def __init__(self, platform:Platform, pickup_list):
        super().__init__()

        #* 道具隨機選擇
        self.buff = random.choice(list(PICKUP_NAME_LIST.keys()))
        self.image = pygame.transform.scale(pickup_list[self.buff], (pickup_list[self.buff].get_size()[0]/3, pickup_list[self.buff].get_size()[1]/3))
    
        #* 定位道具(追蹤平台)
        self.rect = self.image.get_rect()
        self.rect.centerx = platform.rect.centerx
        self.rect.bottom = platform.rect.top-1
        
        #* 該道具跟隨的平台
        self.platform = platform
    
        #! pickup碰撞箱顯示
        # pygame.draw.rect(self.image, ORANGE, (0,0,self.rect.width,self.rect.height), 2)
        
        #* 道具pos，因為目前使用之velocity為int，不用計算float，故不採用pos
        # self.pos = [float(self.rect.centerx), float(self.rect.centery)]
    
    def update(self):
        self.rect.centery += self.platform.velocity[1]
        self.rect.centerx += self.platform.velocity[0]
        if self.rect.top > HEIGHT:
            self.kill()