
#*################################################################
#*                                                               #
#*   .::: .:::. :::::. .:::.    ::: :::::.  ::::.  ::.  ::       #
#*  `::. :::.. ::  :: :::..    ::  ::  ::   ::    `::.::         #
#*   ..:: :: :: ::..:: :: ::    ::  :::::.   ::     .:::.        #
#*    ::: :: :: :::::' `:::'    ::  ::  ::  ::::   ::'  ::       #
#*                                                               #
#*                    <<CLOUDY ADVENTURE>>                       #
#*                          v1.2.0                               #
#*             All Images are generated By Gemini 3.5            #
#*   All codes are written by human, it's not a generated game   #
#*                       Author : Rix                            #
#*                                                               #
#*################################################################

import pygame
import random
from Settings import *

class Platform(pygame.sprite.Sprite):

    def __init__(self, y_speed, platform_list, isfirst):
        super().__init__()
        
        self.choice = random.randint(0,2)
        if self.choice == 0:
            self.image = pygame.transform.scale(platform_list[self.choice], (platform_list[self.choice].get_size()[0]/2, platform_list[self.choice].get_size()[1]/5))
        elif self.choice == 1:
            self.image = pygame.transform.scale(platform_list[self.choice], (platform_list[self.choice].get_size()[0], platform_list[self.choice].get_size()[1]/2))
        elif self.choice == 2:
            self.image = pygame.transform.scale(platform_list[self.choice], (platform_list[self.choice].get_size()[0], platform_list[self.choice].get_size()[1]/2))
        
        self.rect = self.image.get_rect()
        
        #! platform的碰撞箱測試
        # self.rect.inflate(-20,-20)
        # pygame.draw.rect(self.image, ORANGE, (0,0,self.rect.width,self.rect.height), 2)
        
        self.rect.top = 15
        if isfirst:
            self.rect.centerx = WIDTH/2
        else:
            self.rect.centerx = random.randint(self.rect.width//2+30, WIDTH-self.rect.width//2-30)
            
        self.pos = [float(self.rect.centerx), float(self.rect.centery)]
        self.velocity = [random.choice(list(PLATFORM_X_SPEED)), y_speed]
        
    
    def update(self): 
        self.border()
        self.rect.centery += self.velocity[1]
        self.rect.centerx += self.velocity[0]
        if self.rect.top > HEIGHT:
            self.kill()
    
    def border(self):
        if self.rect.left <= 0 or self.rect.right >= WIDTH:
            self.velocity[0] *= -1
    
            

