
#*################################################################
#*                                                               #
#*   .::: .:::. :::::. .:::.    ::: :::::.  ::::.  ::.  ::       #
#*  `::. :::.. ::  :: :::..    ::  ::  ::   ::    `::.::         #
#*   ..:: :: :: ::..:: :: ::    ::  :::::.   ::     .:::.        #
#*    ::: :: :: :::::' `:::'    ::  ::  ::  ::::   ::'  ::       #
#*                                                               #
#*                    <<CLOUDY ADVENTURE>>                       #
#*                          v1.2.0                               #
#*             All Images are generated By Gemini 3.5            #
#*   All codes are written by human, it's not a generated game   #
#*                       Author : Rix                            #
#*                                                               #
#*################################################################

import pygame
import os
from Settings import *

class Player(pygame.sprite.Sprite):

    def __init__(self):
        super().__init__()

        self.front_p = pygame.image.load(os.path.join("img", "front_player.png")).convert_alpha()
        self.jump_p = pygame.image.load(os.path.join("img", "jump_player.png")).convert_alpha()
        self.walk_p = pygame.image.load(os.path.join("img", "walk_player.png")).convert_alpha()
        
        #* 玩家渲染
        self.image = pygame.transform.scale(self.front_p, PLAYER_PIC_SIZE)
        self.rect = self.image.get_rect()
        self.rect.center = (WIDTH/2, 15)
        
        #* 玩家圖片、音檔
        self.walk_player = pygame.transform.scale(self.walk_p, PLAYER_PIC_SIZE)
        self.walk_L_player = pygame.transform.flip(self.walk_player, True, False) 
        self.jump_player = pygame.transform.scale(self.jump_p, PLAYER_PIC_SIZE)
        self.jump_L_player = pygame.transform.flip(self.jump_player, True, False) 
        
        self.pop_sound = pygame.mixer.Sound(os.path.join("sound", "pop.mp3"))
        self.jump_sound = pygame.mixer.Sound(os.path.join("sound", "jumping.mp3"))
        self.oof_sound = pygame.mixer.Sound(os.path.join("sound", "oof.mp3"))
        
        #* 處理玩家位置、速度、加速度
        self.pos = [float(self.rect.centerx), float(self.rect.centery)]
        self.velocity = [0,0]
        self.acceleration = [PLAYER_ACCELERATION,0]
        
        #* 處理玩家能力數值
        self.player_jump_v = PLAYER_JUMP_V
        self.player_x_speed = PLAYER_X_SPEED
        self.g = G
        
        #* 玩家是否站在平台
        self.is_stand_on_platform = False
        
        #* 玩家能力增益
        self.buffList = [False, False, False, False]
        self.buffTimer = [0,0,0,0]
        
    def update(self, platform_group, pickup_group):
        # self.hitbox()
        self.position_change()
        self.timer_detect()
        self.key_event()
        self.gravity()
        self.check_platform_collide(platform_group)
        self.check_pickup_collide(pickup_group)
        self.animate()
        # self.border()
        
    def gravity(self):
        if self.is_stand_on_platform:
            return
        
        if self.rect.top >= HEIGHT:
            self.oof_sound.play()
            self.kill()
            return
        
        self.velocity[1] += self.g
        self.pos[1] += self.velocity[1]
        self.rect.centery = self.pos[1]
    
    def position_change(self):
        self.pos[0] += self.velocity[0]
        self.rect.centerx = self.pos[0]
        
    #! 偵測地面
    def border(self):
        if self.rect.bottom > HEIGHT:
            self.rect.bottom = HEIGHT

    def jump(self):
        self.jump_sound.play()
        self.velocity[1] += self.player_jump_v
        self.pos[1] += self.velocity[1]
        self.rect.centery = self.pos[1]

    def key_event(self):
        kp = pygame.key.get_pressed()
        if kp[pygame.K_LEFT] : self.velocity[0] = self.player_x_speed*-1
        if kp[pygame.K_RIGHT] : self.velocity[0] = self.player_x_speed
            
        if kp[pygame.K_UP]:
            if self.is_stand_on_platform:
                self.is_stand_on_platform = False
                self.jump()
                
    def animate(self):
        kp = pygame.key.get_pressed()
                
        if kp[pygame.K_UP]:
            self.image = self.jump_player
            if kp[pygame.K_LEFT]: self.image = self.jump_L_player
        else:      
            if kp[pygame.K_LEFT]: self.image = self.walk_L_player
            if kp[pygame.K_RIGHT]: self.image = self.walk_player      
                
    def check_platform_collide(self, platform_group):
        self.is_stand_on_platform = False

        hits = pygame.sprite.spritecollide(self, platform_group, False)

        for platform in hits:
            if self.velocity[1] >= 0:
                self.rect.bottom = platform.rect.top   
                self.pos[1] = float(self.rect.centery) 
                self.velocity[1] = platform.velocity[1]        
                self.velocity[0] = platform.velocity[0]       
                self.is_stand_on_platform = True       
                break                                  
                        
    def check_pickup_collide(self, pickup_group):
        hits = pygame.sprite.spritecollide(self, pickup_group, True)
        for pickup in hits:
            if pickup.buff == 0:
                self.pop_sound.play()
                self.player_x_speed = PLAYER_X_SPEED*PICKUP_SPEED_RATIO
                self.buffList[0] = True
                self.buffTimer[0] = POWERUP_TIME*60
                
            if pickup.buff == 1:
                self.pop_sound.play()
                self.player_jump_v = PLAYER_JUMP_V*PICKUP_JUMPVELOCITY_RATIO
                self.buffList[1] = True
                self.buffTimer[1] = POWERUP_TIME*60
                
            if pickup.buff == 2:
                self.pop_sound.play()
                self.g = G*PICKUP_GRAVITY_RATIO
                self.buffList[2] = True
                self.buffTimer[2] = POWERUP_TIME*60
    
    def timer_detect(self):
        #* 玩家X速度增益1.5倍
        if self.buffList[0]:
            self.buffTimer[0] -= 1
            if self.buffTimer[0] <= 0:
                self.buffTimer[0] = 0
                self.buffList[0] = False
                self.player_x_speed = PLAYER_X_SPEED
        
        #* 玩家跳躍增益1.5倍
        if self.buffList[1]:
            self.buffTimer[1] -= 1
            if self.buffTimer[1] <= 0:
                self.buffTimer[1] = 0
                self.buffList[1] = False
                self.player_jump_v = PLAYER_JUMP_V
        
        #* 玩家掉落慢速增益
        if self.buffList[2]:
            self.buffTimer[2] -= 1
            if self.buffTimer[2] <= 0:
                self.buffTimer[2] = 0
                self.buffList[2] = False
                self.g = G
    
    #! player的碰撞箱顯示
    def hitbox(self):
        pygame.draw.rect(self.image, PURPLE, (0,0,self.rect.width, self.rect.height), 2)